### ISSUE TITLE
Option to receive warning instead of error

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/assertr#31]
It would be helpful to allow for warnings rather than errors.  I think the way to do this would be to allow each testing function an argument like `warn`, but the default go to a package-level option (`options(assert_warn=FALSE)`) which is false by default.

**Comment by tonyfischetti** [comment]
Thanks for the suggestion! Yeah, there definitely has to be a way to warn instead of error, and there also needs to be a way (if warn is `FALSE`) to concatenate the messages and display all failures at the end of the checks. I'm still trying to think of the most elegant way to do this, because the solution to the later problem might inform the implementation of the solution to the former problem.

**Comment by tonyfischetti** [comment]
As of commit 2b638015c v(2.0!), this can be achieved by specifying `just_warn` in each verbs' `error_fun` argument. There are also other options... check out `help("success_and_error_functions")`

Thanks for the idea and feedback! Let me know if you have any questions! :)

**Comment by noamross** [comment]
I really like `error_append()`, so I can save the processed object and inspect errors separately.
